### ISSUE TITLE
Add custom odom model for Rosie

### ISSUE THREAD

**Issue by spmaniato** [tailosinc/navigation#1]
#### TODO
- [x] Start with code for `ODOM_MODEL_OMNI_CORRECTED`
- [x] ~~Separate translational velocity into `vx` and `vy`~~
- [x] Calculate amount of strafing distance and direction in body frame
- [ ] Understand this: `delta_strafe_hat = 0 + pf_ran_gaussian(strafe_hat_stddev);`
  - Why is the mean `0` and not `delta_trans` or something similar?
- [x] Possibly add new parameter, `alpha6` (rotation noise when strafing)
- [x] Bias random sampling when it comes to strafing
- [x] Update ROS API with new param, `odom_alpha6`
- [x] Test in simulation - Looks promising, but hard to tell
- [x] Test on actual robot
  - Looks promising. But tuning depends heavily on brush and carpet.

**Comment by spmaniato** [comment]
Working draft added: 44740435988c01a3f62a60c289751b71649d5848
